# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Uuid(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, uuid: str=None):  # noqa: E501
        """Uuid - a model defined in Swagger

        :param uuid: The uuid of this Uuid.  # noqa: E501
        :type uuid: str
        """
        self.swagger_types = {
            'uuid': str
        }

        self.attribute_map = {
            'uuid': 'uuid'
        }
        self._uuid = uuid

    @classmethod
    def from_dict(cls, dikt) -> 'Uuid':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The uuid of this Uuid.  # noqa: E501
        :rtype: Uuid
        """
        return util.deserialize_model(dikt, cls)

    @property
    def uuid(self) -> str:
        """Gets the uuid of this Uuid.


        :return: The uuid of this Uuid.
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid: str):
        """Sets the uuid of this Uuid.


        :param uuid: The uuid of this Uuid.
        :type uuid: str
        """

        self._uuid = uuid
